name: Deploy to NPM Registry

on:
  push:
    branches:
      - dev
      - master

jobs:
  build-and-push-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: ["multisig", "stream"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
        working-directory: ./packages/${{ matrix.packages }}

      - name: Build Library
        run: npm run build
        working-directory: ./packages/${{ matrix.packages }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          working_directory: ./packages/${{ matrix.packages }}
          tag_format: "${{ matrix.packages}}-v${version}"
