name: Deploy to NPM Registry

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-push-treasury:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/multisig

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Library
        run: npm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
