name: Deploy Stream to NPM Registry

on:
  push:
    branches:
      - dev
      - master
    paths:
      - "packages/stream/**"

jobs:
  build-and-push-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
        working-directory: ./packages/stream

      - name: Build Library
        run: npm run build
        working-directory: ./packages/stream

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          working_directory: ./packages/stream
          tag_format: "stream-v${version}"
